### ISSUE TITLE
Advance a REST friendly WFS API

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ideas#12]
**Background**

WFS new revision will provide a more friendly API interface for developers. There  has been some discussion about making WFS 2.x a more REST-like service  (e.g. [OGC Testbed 11 REST Interface Engineering Report](https://portal.opengeospatial.org/files/?artifact_id=64860) and also a possibility to advance a  WFS 3.0. More information [June TC 2017 closing plenary report: Thoughts on the next version of the WFS standard](https://portal.opengeospatial.org/files/?artifact_id=74678) (only available to members).

**The new WFS should:**

1) Follow a REST  interface and be written in the OpenAPI 3.0 Spec
2) Support the Spatial Data on the Web Best Practices, such as:

   - Consistency with HTTP needs to be improved in general – currently mainly a tunnel for messages, implementations not conforming to the HTTP standard, which breaks the Web architecture
Support for HTTPS
   - HTML support not only for the capabilities, but for all resources, including requirements for the interaction with clients like links to the data itself, etc.
   - JSON support for all resources (also for schema description, capabilities, queries, etc.) – NOTE: continued support for XML/GML

3) Provide a convenient default conformance class:
   - use a geodetic WGS84 coordinate reference system as the default CRS 
   - be restricted to GML-SF0 schemas or  GeoJSON	

4) Based as much as possible one existing OGC standards
   - evolution from the existing OGC baseline and its implementations
   - WFS/FES 3.0 interface should be mapable to an WFS/FES 2.0 implementation

**The possible deliverables are as follows:**

- Documentation
   - Draft standard document to be submitted to the TC as Swagger documentation following  OpenAPI 3.0 Spec
   - Tutorial for client implementation (maybe as part of the OpenAPI)
- Servers
   - WFS 2.0 Server
   - WFS 3.0 providing a simple API as proxy to WFS 2.0 
   - WFS 3.0 providing a simple API as a front end for a vector a database
- Clients   
   - Mobile client that invokes the WFS 3.0 simple API (SDK mobile developer)
   - Web client that invokes the WFS 3.0 simple API (Javascript library)
   - Other client that invokes the WFS 3.0 simple API 
- Compliance
   - Reference implementation with data of interested that can be use of useful tutorials
   - Executable test suite

**Comment by cportele** [comment]
I have now submitted a WFS change request for this: 

http://ogc.standardstracker.org/show_request.cgi?id=488

The list of potential deliverables looks good. Let me add a few ideas of what could be potential aspects to explore in addition to what has been noted above:

* We need to get the resources right. Currently we have service capabilities which mix service and data metadata, schemas, service metadata (19119) and data metadata (19115) in catalogues - partly redundant and often inconsistent with the capabilities, etc. I think we need to explore a more natural and more holistic view like datasets, distributions (WFS, WMS, file for download, etc. are all distributions of a dataset), etc. This is quite different from the OWS model where datasets are not a concept, but services are. Using datasets and distributions as resources would also make it more aligned with DCAT, schema.org, etc. That topic is related to the role of capabilities. I think we should take a step back and see how we describe the dataset and its distributions like WFS in a clearer way, potentially across the range of current WxS services.
* What should be required from HTML representations and what should be left to implementers? Can we identify recommendations? This is related both to testability of requirements and how rigid the standard should be. Probably not rigid at all, and more about recommendations, but it might be worth to explore that a bit more as HTML is not something OGC has really looked at so far.
* When does it make sense to have HTML pages for features and when is it "overkill"?
* How to improve indexing by search engines? Will sitemaps for all resources help?
* Links to related resources are what makes the Web a web. Are there any low hanging fruits for providing useful links to other resources?
* Consistency with the OWS Common Security standard (should be avialable when TB 14 starts).
* The current WFS and FES standards do not conform to the ModSpec policy. How can we transform the standard in a consistent way to conform to that policy?
* Mandate any encodings (XML, JSON, HTML) or leave it open? To what extent?

Additional thoughts can be found in the results of the Geonovum "Spatial Data on the Web" testbed from early 2016: http://geo4web-testbed.github.io/topic4/

Note that a requirement for the proxy approach is that the WFS 2.0 supports “startIndex” and “count” so that paged access to data is possible.

**Comment by dr-shorthair** [comment]
> When does it make sense to have HTML pages for features and when is it "overkill"?

I would guess 'always' and 'never'. 
Since you can request any individual feature through legacy WFS, a HTML view can always be styled from this.

I would generally support a shift to a more resource (feature) oriented paradigm. 
But also recognize that some resources are for accepting requests or data that create new resources (i.e. respond to POST operations). These will be distinct from the resources that are more like data already.

**Comment by lieberjosh** [comment]
Where does linking play a role in this idea? Links between features and between feature components that provide more "webbiness" is a major recommendation of the SDWWG. This includes both identification of features / feature components, and a way to use link relations / predicates sensibly to help users / clients to traverse such links.

**Comment by serich** [comment]
Regarding Deliverable 3 "Documentation", sub-bullet 2 "Swagger documentation providing guidance for client development", I would urge that we skip the Swagger 2.0 API Spec and opt instead for an API that conforms to the new (as of summer, 2017) OpenAPI 3.0 Spec (https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md). The latter spec contains many breaking changes (improvements) over the former Spec, in addition to a more open governance approach.

**Comment by prushforth** [comment]
@lieberjosh One of the [core goals of MapML](http://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#user-experience) is to enable linking between features or parts of features.  If WFS was able to serve MapML, this could be a shared goal and work item. MapML is a document-oriented vocabulary for map content on the web.  It allows encoding of features, tiles and images, so far.

**Comment by ingosimonis** [comment]
A lot of WFS 3.0 REST work is now ongoing in Testbed-14's NextGen thread.
