### ISSUE TITLE
Quality of Service Experience Part I - Test Recommendations in OGC Discussion Paper - 049

### ISSUE THREAD

**Issue by CindyMitchell** [opengeospatial/ideas#33]
The OGC Quality of Service Experience (QoSE) Domain Working Group have developed a discussion paper entitled "Ensuring Quality of User Experience with OGC Web Mapping Services" that identifies and describes issues often encountered by users of OGC web mapping services that affect the quality of their experience, and also provides an assessment framework for identifying issues and measuring quality, along with potential solutions and guidance to improve the usability of services. 

The assessment framework for measuring quality of experience and the associated recommendations for improving service quality are intended to benefit human end-users who need to rapidly assimilate and use web mapping visualizations to answer questions or input into analysis. In other words, they need to be able to make sense of the information OGC web mapping service provides them.

Suggested for OGC Testbed 14 is a focus on the usability issues presented in the discussion paper and a test of the recommended solutions and best practices to make web mapping services more usable and consumable to a person viewing/combining/querying the data in a web map client. An important aspect of this test is to identify where recommendations in Discussion Paper 17 - 049 can be acted upon by a human actor (the person(s) creating the web mapping service, or if a usability issue is a result of the web map service specification itself.

The draft discussion paper can be found here: https://docs.google.com/document/d/13DCBYBR7t7AaZlRBIlPHSidoqt6xGJ0AERlBT4I0rM0/edit?usp=sharing

**Comment by tomLandry** [comment]
Transmitting that to my team, thanks.

**Comment by prushforth** [comment]
Hi @CindyMitchell , I am still reading the discussion paper, but quickly looking over the use cases I find myself talking to myself, saying "Yes!!!".  

I think there are a lot of common themes between this and the Maps for HTML initiative, which as you know is part of Testbed 13.  We are talking about integration of Map Markup Language ( MapML ) with existing OGC services (currently, this is operational for WMTS and WMS, but perhaps more are possible).

For reference, here is the link to the [Use Cases and Requirements developed by Maps for HTML](http://maps4html.github.io/HTML-Map-Element-UseCases-Requirements/#introduction) and shared with the Web development community.  One of the key drivers for Maps for HTML is to enable collaboration between the Web mapping community and the greater Web developer / author community, so that we all keep in focus the fact that the platform being targeted is the Web.

I'll finish reading the QoSE discussion paper, then maybe we can chat again to see if there are common points of interest that we can collaborate over.

**Comment by CindyMitchell** [comment]
Good to hear Peter; yes, let's talk soon!
